services:
  frontend:
    image: ${ECR_REGISTRY}/pulse-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pulse_network

  backend:
    image: ${ECR_REGISTRY}/pulse-backend:latest
    expose:
      - "5000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - pulse_network

  db:
    image: mysql:8.2
    command: --innodb-buffer-pool-size=256M --max-connections=64
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pulse_network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - pulse_network

  prometheus:
    image: prom/prometheus:latest
    container_name: pulse_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - pulse_network

  grafana:
    image: grafana/grafana:latest
    container_name: pulse_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - pulse_network

volumes:
  db_data:
  prometheus_data:
  grafana_data:

networks:
  pulse_network:
    driver: bridge