services:
  # Container 1: Frontend Web Server & Reverse Proxy
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pulse_network

  # Container 2: Backend API
  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - pulse_network

  # Container 3: MySQL Database
  db:
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pulse_network

# Persistent storage volume for MySQL..
volumes:
  db_data:

# Private bridge network for container communication
networks:
  pulse_network:
    driver: bridge